module.exports = {
  plugins: [
    'stylelint-selector-bem-pattern',
  ],
  rules: {
    'at-rule-empty-line-before': ['always', {
      except: ['blockless-group'],
      ignore: ['after-comment'],
    }],
    'at-rule-no-vendor-prefix': true,
    'block-closing-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always-multi-line',
    'block-closing-brace-space-before': 'always-single-line',
    'block-no-empty': true,
    'block-opening-brace-newline-after': 'always-multi-line',
    'block-opening-brace-space-after': 'always-single-line',
    'block-opening-brace-space-before': 'always-multi-line',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'comment-empty-line-before': 'always',
    'comment-whitespace-inside': 'always',
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-block-semicolon-newline-after': 'always-multi-line',
    'declaration-block-semicolon-space-after': 'always-single-line',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-block-single-line-max-declarations': 1,
    'declaration-colon-newline-after': 'always-multi-line',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    'function-calc-no-unspaced-operator': true,
    'function-comma-newline-after': 'always-multi-line',
    'function-comma-space-after': 'always-single-line',
    'function-comma-space-before': 'never',
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-parentheses-newline-inside': 'always-multi-line',
    'function-parentheses-space-inside': 'never-single-line',
    'function-url-quotes': 'double',
    'function-whitespace-after': 'always',
    indentation: 2,
    'max-empty-lines': 1,
    'max-line-length': [80, {
      ignore: 'non-comments',
    }],
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',
    'media-query-list-comma-newline-after': 'always-multi-line',
    'media-query-list-comma-space-after': 'always-single-line',
    'media-query-list-comma-space-before': 'never',
    'media-query-parentheses-space-inside': 'never',
    'no-eol-whitespace': true,
    'no-missing-eof-newline': true,
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'number-zero-length-no-unit': true,
    'root-no-standard-properties': true,
    'rule-nested-empty-line-before': 'always-multi-line',
    'rule-no-shorthand-property-overrides': true,
    'rule-non-nested-empty-line-before': 'always-multi-line',
    'rule-properties-order': 'alphabetical',
    'rule-trailing-semicolon': 'always',
    'selector-bem-pattern': {
      preset: 'suit',
      utilitySelectors: /^\.u-(?:[a-z][a-zA-Z0-9]*)+(?:\d{1,2}\\\/\d{1,2})?(?:\\\@[a-zA-Z]{1,3})?$/,
    },
    'selector-combinator-space-after': 'always',
    'selector-combinator-space-before': 'always',
    'selector-list-comma-newline-after': 'always',
    'selector-list-comma-space-before': 'never',
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-root-no-composition': true,
    'string-quotes': 'double',
    'value-list-comma-newline-after': 'always-multi-line',
    'value-list-comma-space-after': 'always-single-line',
    'value-list-comma-space-before': 'never',
    'value-no-vendor-prefix': true,
  },
};
